apiVersion: v1
kind: BuildConfig
metadata:
  name: djangopipeline
  labels:
    name: djangopipeline
  annotations:
    pipeline.alpha.openshift.io/uses: '[{"name": "openshift-django", "namespace": "", "kind": "DeploymentConfig"}]'
spec:
  runPolicy: Serial
  strategy:
    type: JenkinsPipeline
    jenkinsPipelineStrategy:
      jenkinsfile: Jenkinsfile